name: Build Krigga AI APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Container
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: '3.10'
          buildozer-cmd: buildozer -v android debug

      - name: Upload the final APK
        uses: actions/upload-artifact@v4
        with:
          name: KriggaAI-App
          path: bin/*.apk
